#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

script/bootstrap

# Set server port
export JAF_SERVER_PORT=${1:-9000}

echo -e "\n== Starting server on port $JAF_SERVER_PORT =="
grunt watch
